### ISSUE TITLE
[ReaShare] Crash when Paste in Linux

### ISSUE THREAD

**Issue by tkna91** [daniellumertz/DanielLumertz-Scripts#2]
1. Press the "Project" button
1. Press Ctrl+A to Select all the output code and press Ctrl+X to cut
1. Press Ctrl+V to paste
1. Press the "Paste! button

-> ReaShare.lua has crashed

Screencast:

https://github.com/daniellumertz/DanielLumertz-Scripts/assets/102382754/d6fde7e3-4c88-4713-81d9-487afb1414d0

Crash Report:
```
Error: ReaShare Functions.lua:12: attempt to index a nil value (local 'f')

Stack traceback:
	Core.lua:89: in metamethod 'index'
	ReaShare Functions.lua:12: in function 'CreateNewProjectFile'
	ReaShare Functions.lua:118: in function 'CreateProject'
	ReaShare Functions.lua:143: in function 'ReaSharePaste'
	ReaShare.lua:174: in function 'BtnPaste'
	Class - Button.lua:138: in method 'onmouseup'
	Core.lua:888: in field 'Update'
	Core.lua:440: in field 'Main_Update_Elms'
	Core.lua:303: in function <.../REAPER/Scripts/Daniel Lumertz Scripts/ReaShare/Core.lua:299>
		[C]: in function 'xpcall'
	Core.lua:299: in function <.../REAPER/Scripts/Daniel Lumertz Scripts/ReaShare/Core.lua:298>

Lokasenna_GUI:
	v0.1.1
Reaper:
	7.11/linux-x86_64
Platform:
	Other
```

- ReaShare: v0.1.1
- reaper: v7.11-1
- OS: Arch Linux x86_64
- Kernel: 6.7.9-arch1-1
- WM: sway

**Comment by daniellumertz** [comment]
That happened because an invalid path was passed the first time creating a project with Reashare. To change the temporary project path  use the action  `Script: ReaShare Change Temporary Path.lua ` 

Thanks for reporting! I put a new version that checks the path!
