### ISSUE TITLE
[ReaGoTo] Action: Move Next / Move Previous

### ISSUE THREAD

**Issue by tkna91** [daniellumertz/DanielLumertz-Scripts#4]
Thanks for the great script.
It would be useful to have a next/previous action to move to the next/previous region or marker by keyboard or footswitch input.
This is intended for loop-based live performances, etc.

**Comment by daniellumertz** [comment]
You Already can do that, right click a region/marker  and click MIDI Learn 
![image](https://github.com/daniellumertz/DanielLumertz-Scripts/assets/76976666/39af8e0e-d2fa-4ce6-9e39-5695f42b0f29)

**Comment by tkna91** [comment]
I envision an inexpensive footswitch as a type of keyboard, such as the following
https://pcsensor.cn/Foot-Switch?product_category=157

Furthermore, if it is made into an action, it can be made into a custom action, so it can be used for various applications. For example, you can add a Solo/Mute action for each track after this action and use it like a simple Ableton Live session view.

**Comment by daniellumertz** [comment]
This kind of things interest me, but I think is out of the scope of this script, at least for now. It might be better make an extension for what you are asking, to have more time precision!
